### ISSUE TITLE
Clippy warning: attempt to mutate range bound within loop

### ISSUE THREAD

**Issue by alpha-tango-kilo** [sloganking/rs-code-visualizer#9]
Just wanted to check this isn't intended to change the range over which the `for` loop iterates, as it won't. If the code is correct as-is, you can suppress the lint by adding `#[allow(clippy::mut_range_bound)]` above the `for` loop. Otherwise, this may be something to fix?

```
warning: attempt to mutate range bound within loop
   --> src\lib.rs:270:41
    |
270 | ...                   cur_line_x += 1;
    |                       ^^^^^^^^^^
    |
    = note: `#[warn(clippy::mut_range_bound)]` on by default
    = note: the range of the loop is unchanged
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mut_range_bound
```

**Comment by sloganking** [comment]
Thanks for pointing this out. No I wasn't trying to edit the bounds of that loop, Just mutate a variable outside of it, that happened to be part of defining that loop's range. I have updated the code so there is less confusion and this lint goes away.
